# Generated by Django 4.2.2 on 2023-06-08 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=200)),
                ('realtor', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
